#!/system/bin/sh

# Default values for compass calibration,
# this is a workaround only, to make it
# work from the first boot without calibrating
# it manually.

cfg_path="/data/system/yas.cfg"

if [ ! -f $cfg_path ]
then
    echo -n "-1,-3,9,256815,32824,-972243,3,127,127,127,2147483647,2147483647,2147483647,0," > $cfg_path
    chmod 0644 $cfg_path
fi
